version: "3"
services:
  nest-api:
    container_name: nest-api
    restart: unless-stopped
    image: node:14.17-alpine
    build: .
    expose:
      - 3000
    volumes:
      - .:/home/node/app
    ports:
      - "4321:3000"
      command: npm install yarn && yarn install && yarn start:dev
