version: '3'
services:
  template-users-api:
    container_name: template-users-api
    restart: always
    image: mateuswelter01/projects:template-users-api
    networks:
      - templates
    ports:
      - 3002:3000
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure

networks:
  templates:
    driver: overlay
