name: 'deploy-to-swarm'

on:
  push:
    branches:
      - 'master'

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: setup node
  #       uses: actions/setup-node@master
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: Install dependencies
  #       run: |
  #         yarn
  #         yarn build

  # push_to_Docker_Hub:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v2

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: setup node
  #       uses: actions/setup-node@master
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: Install dependencies
  #       run: |
  #         yarn
  #         yarn build

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USER }}
  #         password: ${{ secrets.DOCKER_PASS }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./
  #         file: ./Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_USER }}/projects:template-users-api
  deploy:
    runs-on: [self-hosted, linux, x64]
    # needs: [push_to_Docker_Hub]
    steps:
      - name: install ssh
        run: |
          sudo apt update
          sudo apt install -y openssh-client
      - name: deploy-to-swarm
        run: |
          ssh -V
